---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: self-tracker
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: amol-mgmt
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: self-tracker
    spec:
      project: default
      source:
        repoURL: https://github.com/amold1/for-flux.git
        targetRevision: HEAD
        path: infra
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          abcd: true
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/amold1/for-flux.git
        targetRevision: HEAD
        path: apps
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true